#!/usr/bin/env bash

export _JAVA_AWT_WM_NONREPARENTING=1

workspaces () {
	name = 1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '' '' '' '龎' 'זּ' '' '喇' ''
		let name++
	done
}

workspaces

bspc config border_width 			1
bspc config window_gap 				10
bspc config split_ratio 			0.52

bspc config normal_border_color 	"#282A33"
bspc config focused_border_color 	"#5294E2"
bspc config active_border_color 	"#5294E2"
bspc config presel_feedback_color 	"#5294E2"

bspc config borderless_monocle 		true
bspc config gapless_monocle 		true
bspc config paddingless_monocle 	true
bspc config single_monocle 			true
bspc config focus_follows_pointer 	true

bspc wm --adopt-orphans

~/.config/bspwm/bin/start.sh
